name: Backend deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  backend_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Backend install
        run: npm install
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.8.8
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "amadeusphonebook-backend" 
          heroku_email: "scramblegf@gmail.com"