name: Frontend pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  frontend_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Frontend install
        run: npm run frontend:install
      - name: Frontend lint
        run: npm run frontend:lint
      - name: Frontend test
        run: npm run frontend:test
      - name: Frontend build
        run: npm run frontend:build